config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  get "dashboard/cars", to: "pages#dashboardmycars"
  get "dashboard/bookings", to: "pages#dashboardmybookings"
  resources :cars, only: [:index, :new, :create, :show, :destroy] do
    resources :bookings, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :start_date, :end_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  validates :title, :price, presence: true
  validates :description, length: { minimum: 8 }
  # validates :availability, inclusion: [true, false]
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars
  has_many :bookings
  # validates :username, :first_name, :last_name, :date_of_birth, presence: true
  # validates :username, :email, uniqueness: true

  validate :validate_age

  private

  def validate_age
    if date_of_birth.present? && date_of_birth > 18.years.ago
      errors.add(:date_of_birth, 'You should be over 18 years old.')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :date_of_birth])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :date_of_birth])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
   before_action :authenticate_user!
  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_bookings_path
    else
     render "cars/show"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @markers = [{
        lat: @car.latitude,
        lng: @car.longitude,
        info_window: render_to_string(partial: "info_window", locals: { car: @car }),
        image_url: helpers.asset_url("https://i.pinimg.com/originals/96/7f/08/967f08d24af11b020931ebe21885f05d.jpg")
    }]
    @booking = Booking.new
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    @car.availability = true
    if @car.save
      redirect_to cars_path
    else
      render :new
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to dashboard_cars_path
  end

  private

  def car_params
    params.require(:car).permit(:title, :description, :price, :model_type, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]
  def home

  end

  def dashboardmycars
    @cars_user = []
    Car.all.each do |car|
      if car.user == current_user
        @cars_user<<car
      end
    end
  end

  def dashboardmybookings
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<div class="form">
<h2>Upload Car</h2>
<%= simple_form_for(@car) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :model_type %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Upload", class: "btn btn-primary text-white" %>
<% end %>
</div>

app/views/cars/index.html.erb
<div class="container mb-5">
  <%# <ul class="list_cars"> %>
  <div class="row" >
    <div class="banner-container">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://blogmedia.dealerfire.com/wp-content/uploads/sites/767/2018/08/Row-Of-Used-Cars-For-Sale-At-A-Dealership_b-e1547479966504.jpg)">
      <h2>Have a look at all Cars</h2>
      </div>
    </div>
    <%@cars.each do |car| %>
      <div class="px-3 col-lg-6 col-md-12 col-xs-12 col-sm-12">
      <%= link_to "cars/#{car.id}" do%>
        <div class="card-product">
         <%=
             car.photo.attached? ? cl_image_tag(car.photo.key, crop: :fill, class:"card-img") : image_tag("https://mclaren.scene7.com/is/image/mclaren/Mclaren_Artura_Zenith%20Black_03:crop-16x9?wid=1980&hei=1114", class:"card-img")
              %>
          <div class="card-product-infos">
            <div class= "list_item">
              <%# <div> %>
                <h3><%=car.title%></h3>
                <p><%= car.model_type%></p>
                <p><%= car.price %>$</p>
                <p><%= car.user.first_name%> <%= car.user.last_name %></p>
              <%# </div> %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
<%# </ul> %>
</div>

app/views/cars/new.html.erb
<%= render "cars/form" %>

app/views/cars/show.html.erb
<div class="container mb-5" >
  <div class="row">
    <%# <div id="carouselExampleControls" class="col-8 carousel slide" data-bs-ride="carousel" style="margin: 0; padding: 0;"> %>
      <%# <div class="carousel-inner">
        <div class="carousel-item active"> %>
        <div class="col-8">
           <%= cl_image_tag(@car.photo.key, crop: :fill, class:"card-img-show", alt:"car")%>

        </div>
        <%# </div> %>
        <%# <div class="carousel-item"> %>
          <%# <img src="https://img.autovisie.nl/images/3VprBXVConFcg5hr6TL_p_beYa4=/1280x0/filters:quality(80):format(jpeg):background_color(fff)/https%3A%2F%2Fwww.autovisie.nl%2Fwp-content%2Fuploads%2FFerrari-488-Pista-Duik-in-de-Prijslijst-2.jpg" class="d-block w-100" alt="" > %>
        <%# </div> %>
        <%# <div class="carousel-item"> %>
          <%# <img src="https://static.moniteurautomobile.be/imgcontrol/images_tmp/clients/moniteur/c680-d465/content/medias/images/cars/ferrari/f-488/ferrari--f-488--2018/ferrari--f-488--2018-m-3.jpg" class="d-block w-100" alt=""> %>
        <%# </div> %>
      <%# </div> %>
      <%# <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev"> %>
        <%# <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div> %>
    <div class="p-0 col-4 map-box">
    <div id="my-map" style="width: 100%; height: 100%; border-radius: 5px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>

    <div class="row">
      <div class="col-md-6 col-xl-8 pr-4">
        <div class="text-box-infos">
        <h1>Owners information</h1>
          <p><strong>Title:</strong><%= @car.title %></p>
          <p><strong>Owner:</strong> <%= @car.user.first_name %></p>
          <p><strong>Address:</strong> <%= @car.address %></p>
          <p><strong>Description:</strong> <%= @car.description %></p>
         <div class="price"><p><strong>Price:</strong> <%= @car.price %></p></div>
        </div>
      </div>
      <div class="col-md-6 col-xl-4 mt-3">
        <div class="booking-form">
          <%= simple_form_for [ @car, @booking ] do |f| %>
            <%= f.input :start_date %>
            <%= f.input :end_date %>
            <%= f.submit "Submit booking", class: "btn btn-primary w-100 text-white"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazingRentals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div style="min-height: 60vh;">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <!--<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
  </body>
</html>

app/views/pages/_sidebar_bookings.html.erb
<div class="sidebar text-white">
  <h1 class="text-white">Hey <%= current_user.first_name %></h1>
  <span><%= link_to "My cars", dashboard_cars_path, class:"text-white" %></span>
  <span> <strong> <%= link_to "My bookings", dashboard_bookings_path, class:"text-white" %></strong></span>
</div>

app/views/pages/_sidebar_cars.html.erb
<div class="sidebar">
  <h1 class="text-white">Hey <%= current_user.first_name %></h1>
  <span> <strong><%= link_to "My cars", dashboard_cars_path, class:"text-white" %></strong> </span>
  <span><%= link_to "My bookings", dashboard_bookings_path, class:"text-white" %></span>
</div>

app/views/pages/dashboardmybookings.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <%= render "sidebar_bookings" %>
    </div>
    <div class="col-8">
      <%@user.bookings.each do |booking| %>
        <div class="px-3">
        <%= link_to car_path(booking.car) do%>
          <div class="card-product" style="height:190px;">
          <%=
              booking.car.photo.attached? ? cl_image_tag(booking.car.photo.key, crop: :fill, class:"card-img") : image_tag("https://mclaren.scene7.com/is/image/mclaren/Mclaren_Artura_Zenith%20Black_03:crop-16x9?wid=1980&hei=1114", class:"card-img")
                %>
            <div class="card-product-infos">
              <div class= "list_item">
                <h3><%=booking.car.title%></h3>
                <p><%=booking.start_date %></p>
                <p><%=booking.end_date%></p>
              </div>
            </div>
          </div>
          <div style="text-align: right;">
          <%= link_to "Delete", car_booking_path(booking.car, booking), method: :delete, data: {confirm: "Are you sure?"}, class:"btn mb-5", style:"color: white; background-color: #2892D7; border: none;" %>
          </div>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboardmycars.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <%= render "sidebar_cars" %>
    </div>

    <div class="col-8">
      <%@cars_user.each do |car| %>
        <div>
          <div class="px-3">
            <%= link_to car_path(car) do%>
              <div class="card-product" style="height:190px;">
                  <%=
                  car.photo.attached? ? cl_image_tag(car.photo.key, crop: :fill, class:"card-img") : image_tag("https://mclaren.scene7.com/is/image/mclaren/Mclaren_Artura_Zenith%20Black_03:crop-16x9?wid=1980&hei=1114", class:"card-img")
                    %>
                <div class="card-product-infos">
                  <div class= "list_item">
                    <h3><%=car.title%></h3>

                    <p><%= car.model_type%></p>
                    <p><%= car.price %>$</p>
                    <p><%= car.user.first_name%> <%= car.user.last_name %></p>
                  </div>
                </div>
             </div>
            <div style="text-align: right;">
              <%= link_to "Delete", car_path(car), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-primary mb-5", style:"color: white; background-color:$blue; border: none;" %>
            </div>
            <%#= link_to "Delete", car_path(car), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-primary mb-5" %>
            <% end %>
            </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
<span class="brand-name">Amazing Rentals</span>
<h3>The amazing platform to rent a car!</h3>
<%= link_to "Explore our cars", "cars#index", class:"btn-home"%>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul>
    <a href="#"><li>Help center</li></a>
    <a href="#"><li>About us</li></a>
  </ul>
  <div class="links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>Copyright @Amazing Rentals</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "car logo svg.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Upload car", new_car_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "profile picture.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My cars", dashboard_cars_path, class: "dropdown-item" %>
              <%= link_to "My bookings", dashboard_bookings_path , class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>